syntax = "proto3";

package ares.messages;

import "google/protobuf/empty.proto";

// this service can be used to either add a new user or update an existing one
service UserManagement {
	rpc Register(RegistrationRequest) returns (ManagementResponse);
	rpc UpdateUser(RegistrationRequest) returns (ManagementResponse);
	rpc DeleteUser(UserDeleteRequest)  returns (ManagementResponse);
	rpc GetUsers(google.protobuf.Empty) returns (UsersResponse);
	rpc GetUser(UserRequest) returns (UserResponse);
}

message RegistrationRequest {
	UserInfo user_info = 1; // information about the user being registered/updated
	string password = 2; // the password in plain text
}

message ManagementResponse {
	bool success = 1; // whether or not the registration was successful
	repeated string errors = 2; // if success is false, this field will contain the reasoning for why
}

message UserInfo {
	string user_name = 1; // user name for the user
	string email = 2; // email for the user
	repeated string roles = 3; // the roles assigned to this user
}

message UserRequest {
	string user_name = 1; // the user name of the requested user
}

message UsersResponse {
	repeated UserInfo users = 1; // all registered users
}

message UserResponse {
	UserInfo user = 1; // requested user
	bool success = 2; // whether getting the user succeeded
	string error = 3; // error in case could not get user
}

message UserDeleteRequest {
	string user_name = 1; // user name of the user to delete
}

