// <auto-generated />
using System;
using AresService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AresService.Migrations.Postgres.Migrations
{
    [DbContext(typeof(AresDbContext))]
    partial class AresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ares.Datamodel.AnalysisOverview", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalyzerInfo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ExperimentOverviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Result")
                        .HasColumnType("double precision");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentOverviewId")
                        .IsUnique();

                    b.ToTable("AnalysisOverview");
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.Analysis", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorString")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<float>("Result")
                        .HasColumnType("real");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("UniqueId");

                    b.ToTable("Analyses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerCapabilities", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalyzerInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SettingsSchema")
                        .HasColumnType("jsonb");

                    b.Property<long>("TimeoutSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("UniqueId");

                    b.HasIndex("AnalyzerInfoId")
                        .IsUnique();

                    b.ToTable("AnalyzerCapabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("Analyzers", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("AnalyzerInfos");
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalyzerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.HasKey("UniqueId");

                    b.ToTable("AnalyzerSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.AresCampaignTag", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("CampaignTags");
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionStatus", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("UniqueId");

                    b.ToTable("CampaignExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text");

                    b.Property<string>("CampaignNotes")
                        .HasColumnType("text");

                    b.Property<string>("CampaignTags")
                        .HasColumnType("text");

                    b.Property<Guid?>("CloseoutExecutionSummaryUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("StartupExecutionSummaryUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("UniqueId");

                    b.HasIndex("CloseoutExecutionSummaryUniqueId");

                    b.HasIndex("StartupExecutionSummaryUniqueId");

                    b.ToTable("CampaignExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionStatus", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandId")
                        .HasColumnType("text");

                    b.Property<string>("CommandName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StepExecutionStatusUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepExecutionStatusUniqueId");

                    b.ToTable("CommandExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandDescription")
                        .HasColumnType("text");

                    b.Property<string>("CommandId")
                        .HasColumnType("text");

                    b.Property<string>("CommandName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("StepExecutionSummaryUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepExecutionSummaryUniqueId");

                    b.ToTable("CommandExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandResult", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AwaitUserInput")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CommandExecutionSummaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandExecutionSummaryId")
                        .IsUnique();

                    b.ToTable("DeviceCommandResults", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceCommandDescriptor", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputSchema")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OutputSchema")
                        .HasColumnType("jsonb");

                    b.HasKey("UniqueId");

                    b.HasIndex("DeviceInfoId");

                    b.ToTable("DeviceCommandDescriptor");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceConfigs", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SettingsSchema")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceInfos");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceLoggingSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Deltas")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<long>("IntervalMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("LoggingType")
                        .HasColumnType("integer");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceLoggingSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceState", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UniqueId");

                    b.ToTable("DeviceStates");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.RemoteDeviceConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("RemoteDevices", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.ExecutionInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignExecutionSummaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommandExecutionSummaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ExperimentResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LocaltimeOffset")
                        .HasColumnType("text");

                    b.Property<Guid?>("StepExecutionSummaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TimeFinished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeStarted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignExecutionSummaryId")
                        .IsUnique();

                    b.HasIndex("CommandExecutionSummaryId")
                        .IsUnique();

                    b.HasIndex("ExperimentResultId")
                        .IsUnique();

                    b.HasIndex("StepExecutionSummaryId")
                        .IsUnique();

                    b.ToTable("ExecutionInfos", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionStatus", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignExecutionStatusUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExperimentId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignExecutionStatusUniqueId");

                    b.ToTable("ExperimentExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignExecutionSummaryUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExperimentId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ResultOutputPath")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignExecutionSummaryUniqueId");

                    b.ToTable("ExperimentExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentOverview", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ExperimentResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TemplateUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentResultId")
                        .IsUnique();

                    b.HasIndex("TemplateUniqueId");

                    b.ToTable("ExperimentOverviews", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Limits", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<float>("Maximum")
                        .HasColumnType("real");

                    b.Property<float>("Minimum")
                        .HasColumnType("real");

                    b.Property<Guid>("ParameterMetadataUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("UniqueId");

                    b.HasIndex("ParameterMetadataUniqueId");

                    b.ToTable("Limits");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.Planner", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PlannerName")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlannerServiceCapabilitiesUniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("PlannerServiceCapabilitiesUniqueId");

                    b.ToTable("Planner");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerAllocation", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignTemplateUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ParameterUniqueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlannerId")
                        .HasColumnType("uuid");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignTemplateUniqueId");

                    b.HasIndex("ParameterUniqueId");

                    b.HasIndex("PlannerId");

                    b.ToTable("PlannerAllocations", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerConfig", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerServices", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceCapabilities", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("PlannerInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<string>("SettingsSchema")
                        .HasColumnType("jsonb");

                    b.Property<long>("TimeoutSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("UniqueId");

                    b.HasIndex("PlannerInfoId")
                        .IsUnique();

                    b.ToTable("PlannerServiceCapabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceInfo", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerInfos");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerSettings", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PlannerId")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.HasKey("UniqueId");

                    b.ToTable("PlannerSettings");
                });

            modelBuilder.Entity("Ares.Datamodel.Project", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionStatus", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ExperimentExecutionStatusUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("StepId")
                        .HasColumnType("text");

                    b.Property<string>("StepName")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentExecutionStatusUniqueId");

                    b.ToTable("StepExecutionStatuses", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionSummary", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ExperimentExecutionSummaryUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("StepId")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentExecutionSummaryUniqueId");

                    b.ToTable("StepExecutionSummaries", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CampaignTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CampaignTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandMetadata", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandTemplateId")
                        .IsUnique();

                    b.ToTable("CommandMetadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("StepTemplateUniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("UniqueId");

                    b.HasIndex("StepTemplateUniqueId");

                    b.ToTable("CommandTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ExperimentTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalyzerId")
                        .HasColumnType("text");

                    b.Property<Guid?>("CampaignCloseoutId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignExperimentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignStartupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignCloseoutId")
                        .IsUnique();

                    b.HasIndex("CampaignExperimentId")
                        .IsUnique();

                    b.HasIndex("CampaignStartupId")
                        .IsUnique();

                    b.ToTable("ExperimentTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.OutputMetadata", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataSchema")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UniqueId");

                    b.ToTable("OutputMetadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.Parameter", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommandTemplateUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("EnvironmentBased")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ExperimentOverviewUniqueId")
                        .HasColumnType("uuid");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Planned")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlanningMetadataUniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("jsonb");

                    b.Property<string>("VariableArgument")
                        .HasColumnType("text");

                    b.Property<int>("VariableType")
                        .HasColumnType("integer");

                    b.HasKey("UniqueId");

                    b.HasIndex("CommandTemplateUniqueId");

                    b.HasIndex("ExperimentOverviewUniqueId");

                    b.HasIndex("PlanningMetadataUniqueId");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ParameterMetadata", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignTemplateUniqueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommandMetadataUniqueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ExtraInfoUniqueId")
                        .HasColumnType("uuid");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("NotPlannable")
                        .HasColumnType("boolean");

                    b.Property<string>("OutputName")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParameterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlannerDescription")
                        .HasColumnType("text");

                    b.Property<string>("PlannerName")
                        .HasColumnType("text");

                    b.Property<string>("Schema")
                        .HasColumnType("jsonb");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<bool>("UseDefault")
                        .HasColumnType("boolean");

                    b.HasKey("UniqueId");

                    b.HasIndex("CampaignTemplateUniqueId");

                    b.HasIndex("CommandMetadataUniqueId");

                    b.HasIndex("ExtraInfoUniqueId");

                    b.HasIndex("ParameterId")
                        .IsUnique();

                    b.ToTable("ParameterMetadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.StepTemplate", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ExperimentTemplateUniqueId")
                        .HasColumnType("uuid");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsParallel")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("UniqueId");

                    b.HasIndex("ExperimentTemplateUniqueId");

                    b.ToTable("StepTemplates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.Chiller.ChillerState", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double?>("ManifoldTemperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UniqueId");

                    b.ToTable("ChillerStates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.Mfc.MfcState", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AbsolutePressure")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("Gas")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double?>("MassFlow")
                        .HasColumnType("double precision");

                    b.Property<double?>("Setpoint")
                        .HasColumnType("double precision");

                    b.Property<string>("StatusCodes")
                        .HasColumnType("text");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("VolumetricFlow")
                        .HasColumnType("double precision");

                    b.HasKey("UniqueId");

                    b.ToTable("MfcStates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.RestDevice.RestDeviceStateEntity", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UniqueId");

                    b.ToTable("RestDeviceStateEntities", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.RestSerialDevice.RestSerialDeviceStateEntity", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UniqueId");

                    b.ToTable("RestSerialDeviceStateEntities", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.SyringePump.SyringePumpState", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Address")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<double?>("DispensedVolume")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("RateUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VolumeUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("WithdrawnVolume")
                        .HasColumnType("double precision");

                    b.HasKey("UniqueId");

                    b.ToTable("SyringePumpStates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.Tc0304.Tc0304State", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double?>("Probe1Temperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("Probe2Temperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("Probe3Temperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("Probe4Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UniqueId");

                    b.ToTable("Tc0304States", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.TicStepperController.TicStepperControllerState", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("integer");

                    b.Property<long>("CustomStepSize")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MaxAcceleration")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxDeceleration")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxSpeed")
                        .HasColumnType("bigint");

                    b.Property<long>("StartingSpeed")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusMessages")
                        .HasColumnType("text");

                    b.Property<string>("StepMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetPosition")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UniqueId");

                    b.ToTable("TicStepperControllerStates", (string)null);
                });

            modelBuilder.Entity("Ares.Messages.DeviceStates.TubeFurnace.TubeFurnaceStateEntity", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("CurrentTemp")
                        .HasColumnType("double precision");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("SetPointTemp")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UniqueId");

                    b.ToTable("TubeFurnaceStateEntities", (string)null);
                });

            modelBuilder.Entity("Google.Protobuf.WellKnownTypes.Any", b =>
                {
                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("DeviceConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("TypeUrl")
                        .HasColumnType("text");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea");

                    b.HasKey("UniqueId");

                    b.HasIndex("DeviceConfigId")
                        .IsUnique();

                    b.ToTable("Any");
                });

            modelBuilder.Entity("Ares.Datamodel.AnalysisOverview", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentOverview", null)
                        .WithOne("AnalysisOverview")
                        .HasForeignKey("Ares.Datamodel.AnalysisOverview", "ExperimentOverviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerCapabilities", b =>
                {
                    b.HasOne("Ares.Datamodel.Analyzing.AnalyzerInfo", null)
                        .WithOne("Capabilities")
                        .HasForeignKey("Ares.Datamodel.Analyzing.AnalyzerCapabilities", "AnalyzerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", "CloseoutExecutionSummary")
                        .WithMany()
                        .HasForeignKey("CloseoutExecutionSummaryUniqueId");

                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", "StartupExecutionSummary")
                        .WithMany()
                        .HasForeignKey("StartupExecutionSummaryUniqueId");

                    b.Navigation("CloseoutExecutionSummary");

                    b.Navigation("StartupExecutionSummary");
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionStatus", b =>
                {
                    b.HasOne("Ares.Datamodel.StepExecutionStatus", null)
                        .WithMany("CommandExecutionStatuses")
                        .HasForeignKey("StepExecutionStatusUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.StepExecutionSummary", null)
                        .WithMany("CommandSummaries")
                        .HasForeignKey("StepExecutionSummaryUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.CommandResult", b =>
                {
                    b.HasOne("Ares.Datamodel.CommandExecutionSummary", null)
                        .WithOne("Result")
                        .HasForeignKey("Ares.Datamodel.CommandResult", "CommandExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceCommandDescriptor", b =>
                {
                    b.HasOne("Ares.Datamodel.Device.DeviceInfo", null)
                        .WithMany("Commands")
                        .HasForeignKey("DeviceInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.ExecutionInfo", b =>
                {
                    b.HasOne("Ares.Datamodel.CampaignExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "CampaignExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.CommandExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "CommandExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "ExperimentResultId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.StepExecutionSummary", null)
                        .WithOne("ExecutionInfo")
                        .HasForeignKey("Ares.Datamodel.ExecutionInfo", "StepExecutionSummaryId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionStatus", b =>
                {
                    b.HasOne("Ares.Datamodel.CampaignExecutionStatus", null)
                        .WithMany("ExperimentExecutionStatuses")
                        .HasForeignKey("CampaignExecutionStatusUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.CampaignExecutionSummary", null)
                        .WithMany("ExperimentSummaries")
                        .HasForeignKey("CampaignExecutionSummaryUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentOverview", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", null)
                        .WithOne("ExperimentOverview")
                        .HasForeignKey("Ares.Datamodel.ExperimentOverview", "ExperimentResultId");

                    b.HasOne("Ares.Datamodel.Templates.ExperimentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateUniqueId");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Ares.Datamodel.Limits", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.ParameterMetadata", null)
                        .WithMany("Constraints")
                        .HasForeignKey("ParameterMetadataUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.Planner", b =>
                {
                    b.HasOne("Ares.Datamodel.Planning.PlannerServiceCapabilities", null)
                        .WithMany("AvailablePlanners")
                        .HasForeignKey("PlannerServiceCapabilitiesUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerAllocation", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithMany("PlannerAllocations")
                        .HasForeignKey("CampaignTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ares.Datamodel.Templates.ParameterMetadata", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterUniqueId");

                    b.HasOne("Ares.Datamodel.Planning.PlannerServiceInfo", "Planner")
                        .WithMany()
                        .HasForeignKey("PlannerId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Parameter");

                    b.Navigation("Planner");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceCapabilities", b =>
                {
                    b.HasOne("Ares.Datamodel.Planning.PlannerServiceInfo", null)
                        .WithOne("Capabilities")
                        .HasForeignKey("Ares.Datamodel.Planning.PlannerServiceCapabilities", "PlannerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionStatus", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentExecutionStatus", null)
                        .WithMany("StepExecutionStatuses")
                        .HasForeignKey("ExperimentExecutionStatusUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionSummary", b =>
                {
                    b.HasOne("Ares.Datamodel.ExperimentExecutionSummary", null)
                        .WithMany("StepSummaries")
                        .HasForeignKey("ExperimentExecutionSummaryUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandMetadata", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CommandTemplate", null)
                        .WithOne("Metadata")
                        .HasForeignKey("Ares.Datamodel.Templates.CommandMetadata", "CommandTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandTemplate", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.StepTemplate", null)
                        .WithMany("CommandTemplates")
                        .HasForeignKey("StepTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ExperimentTemplate", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithOne("CloseoutTemplate")
                        .HasForeignKey("Ares.Datamodel.Templates.ExperimentTemplate", "CampaignCloseoutId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithOne("ExperimentTemplate")
                        .HasForeignKey("Ares.Datamodel.Templates.ExperimentTemplate", "CampaignExperimentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithOne("StartupTemplate")
                        .HasForeignKey("Ares.Datamodel.Templates.ExperimentTemplate", "CampaignStartupId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.OutputMetadata", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CommandMetadata", null)
                        .WithOne("OutputMetadata")
                        .HasForeignKey("Ares.Datamodel.Templates.OutputMetadata", "UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.Parameter", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CommandTemplate", null)
                        .WithMany("Parameters")
                        .HasForeignKey("CommandTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ares.Datamodel.ExperimentOverview", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ExperimentOverviewUniqueId");

                    b.HasOne("Ares.Datamodel.Templates.ParameterMetadata", "PlanningMetadata")
                        .WithMany()
                        .HasForeignKey("PlanningMetadataUniqueId");

                    b.Navigation("PlanningMetadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ParameterMetadata", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.CampaignTemplate", null)
                        .WithMany("PlannableParameters")
                        .HasForeignKey("CampaignTemplateUniqueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Ares.Datamodel.Templates.CommandMetadata", null)
                        .WithMany("ParameterMetadatas")
                        .HasForeignKey("CommandMetadataUniqueId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Google.Protobuf.WellKnownTypes.Any", "ExtraInfo")
                        .WithMany()
                        .HasForeignKey("ExtraInfoUniqueId");

                    b.HasOne("Ares.Datamodel.Templates.Parameter", null)
                        .WithOne("Metadata")
                        .HasForeignKey("Ares.Datamodel.Templates.ParameterMetadata", "ParameterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExtraInfo");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.StepTemplate", b =>
                {
                    b.HasOne("Ares.Datamodel.Templates.ExperimentTemplate", null)
                        .WithMany("StepTemplates")
                        .HasForeignKey("ExperimentTemplateUniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Google.Protobuf.WellKnownTypes.Any", b =>
                {
                    b.HasOne("Ares.Datamodel.Device.DeviceConfig", null)
                        .WithOne("ConfigData")
                        .HasForeignKey("Google.Protobuf.WellKnownTypes.Any", "DeviceConfigId")
                        .OnDelete(DeleteBehavior.ClientCascade);
                });

            modelBuilder.Entity("Ares.Datamodel.Analyzing.AnalyzerInfo", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionStatus", b =>
                {
                    b.Navigation("ExperimentExecutionStatuses");
                });

            modelBuilder.Entity("Ares.Datamodel.CampaignExecutionSummary", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("ExperimentSummaries");
                });

            modelBuilder.Entity("Ares.Datamodel.CommandExecutionSummary", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceConfig", b =>
                {
                    b.Navigation("ConfigData");
                });

            modelBuilder.Entity("Ares.Datamodel.Device.DeviceInfo", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionStatus", b =>
                {
                    b.Navigation("StepExecutionStatuses");
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentExecutionSummary", b =>
                {
                    b.Navigation("ExecutionInfo");

                    b.Navigation("ExperimentOverview");

                    b.Navigation("StepSummaries");
                });

            modelBuilder.Entity("Ares.Datamodel.ExperimentOverview", b =>
                {
                    b.Navigation("AnalysisOverview");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceCapabilities", b =>
                {
                    b.Navigation("AvailablePlanners");
                });

            modelBuilder.Entity("Ares.Datamodel.Planning.PlannerServiceInfo", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionStatus", b =>
                {
                    b.Navigation("CommandExecutionStatuses");
                });

            modelBuilder.Entity("Ares.Datamodel.StepExecutionSummary", b =>
                {
                    b.Navigation("CommandSummaries");

                    b.Navigation("ExecutionInfo");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CampaignTemplate", b =>
                {
                    b.Navigation("CloseoutTemplate");

                    b.Navigation("ExperimentTemplate");

                    b.Navigation("PlannableParameters");

                    b.Navigation("PlannerAllocations");

                    b.Navigation("StartupTemplate");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandMetadata", b =>
                {
                    b.Navigation("OutputMetadata");

                    b.Navigation("ParameterMetadatas");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.CommandTemplate", b =>
                {
                    b.Navigation("Metadata");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ExperimentTemplate", b =>
                {
                    b.Navigation("StepTemplates");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.Parameter", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.ParameterMetadata", b =>
                {
                    b.Navigation("Constraints");
                });

            modelBuilder.Entity("Ares.Datamodel.Templates.StepTemplate", b =>
                {
                    b.Navigation("CommandTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
