syntax = "proto3";

package tc0304.services;

import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/wrappers.proto";
import "DataModel.proto";
import "Tc0304Config.proto";

service TC0304Rpc {
  rpc GetData(DeviceRequest) returns (DataResponse);
  rpc GetTemperatures(DeviceRequest) returns (GetTemperaturesResponse);
  rpc GetBatteryStatus(DeviceRequest) returns (BatteryStatusResponse);

  rpc Hold(DeviceRequest) returns (google.protobuf.Empty);
  rpc StartStateUpdater(StartStateUpdaterRequest) returns (google.protobuf.Empty);
  rpc StopStateUpdater(DeviceRequest) returns (google.protobuf.Empty);

  rpc GetAllTc0304s(google.protobuf.Empty) returns (GetAllTc0304sResponse);
  rpc UpdateTc0304(UpdateTc0304Request) returns (google.protobuf.Empty);
	rpc RemoveTc0304(Tc0304Request) returns (google.protobuf.Empty);
	rpc AddTc0304(config.Tc0304Config) returns (google.protobuf.Empty);
  rpc GetProbeNames(Tc0304Request) returns (tc0304.data_model.ProbeNames);
}

message Tc0304Request {
  string tc0304_id = 1;
}

message UpdateTc0304Request {
  string id = 1;
  config.Tc0304Config config = 2;
}

message GetTemperaturesResponse {
  optional double probe_1_c = 1;
  optional double probe_2_c = 2;
  optional double probe_3_c = 3;
  optional double probe_4_c = 4;
}

message BatteryStatusResponse {
  bool battery_low = 1;
}

message GetAllTc0304sResponse {
  repeated DeviceDescription devices = 1;
}

message DeviceDescription {
  string id = 1;
  string name = 2;
}

message DataResponse {
  tc0304.data_model.Data data = 1;
}

message StartStateUpdaterRequest {
  DeviceRequest device_request = 1;
  google.protobuf.Duration interval = 2;
}

message ConnectRequest {
  string device_id = 1; // id of the data logger
  string port_name = 2; // name of the port
}

message ConnectResponse {
  bool connected = 1; // whether or not the device successfully connected
}

message DeviceRequest {
  string device_id = 1;
}