<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Proto\DataModel.proto" />
    <None Remove="Proto\MK4SConfig.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.32.1" />
    <PackageReference Include="ARES.Datamodel" Version="0.13.0-beta.3" GeneratePathProperty="True" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Core\Ares.Core.csproj" />
    <ProjectReference Include="..\Ares.Device.USB\Ares.Device.USB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\DataModel.proto" GrpcServices="None" ProtoRoot="Proto" />
		<Protobuf Include="Proto\Services.proto" ProtoRoot="Proto" />
		<Protobuf Include="Proto\MK4SConfig.proto" GrpcServices="None" ProtoRoot="Proto" />
  </ItemGroup>

</Project>
