<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Proto\DataModel.proto" />
    <None Remove="Proto\MK4SConfig.proto" />
    <None Remove="Proto\Services.proto" />
  </ItemGroup>

	<PropertyGroup>
		<DataModelProtoPath>$(PkgARES_Datamodel)\Proto\datamodel\</DataModelProtoPath>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ARES.Datamodel" Version="0.15.1-beta.1" GeneratePathProperty="True" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Core\Ares.Core.csproj" />
    <ProjectReference Include="..\Ares.Device.Rest\Ares.Device.Rest.csproj" />
    <ProjectReference Include="..\Ares.Device.USB\Ares.Device.USB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\DataModel.proto" GrpcServices="None" />
    <Protobuf Include="Proto\MK4SConfig.proto" GrpcServices="None" />
    <Protobuf Include="Proto\Services.proto" ProtoRoot="Proto" AdditionalImportDirs="$(DataModelProtoPath)" />
  </ItemGroup>

</Project>
