using Ares.Datamodel;
using Ares.Datamodel.Analyzing;
using Ares.Datamodel.Connection;
using Ares.Datamodel.Planning;
using Ares.Datamodel.Templates;

namespace Ares.Core.Planning;

public interface IPlannerService
{
  /// <summary>
  /// Optional name for the planner service (can be useful when multiple planners of same type and version have to be used)
  /// </summary>
  string Name { get; set; }

  /// <summary>
  /// The planner service itself should have a tpye name that it reports regardless of what name the user has given it.
  /// So for example the type could be "BoraasPlanner" while the user calls it "My Amazing Planner"
  /// </summary>
  string Type { get; }

  /// <summary>
  /// Version of the planner service.
  /// </summary>
  string Version { get; }

  /// <summary>
  /// The unique id for identifying the planner service.
  /// </summary>
  string UniqueId { get; internal set; }

  /// <summary>
  /// Optional description of the planner service.
  /// </summary>
  string Description { get; }

  /// <summary>
  /// Initializes the planner adapter, including verifying the connection status
  /// </summary>
  /// <returns></returns>
  Task Init();

  /// <summary>
  /// Provides an observable for the <see cref="State"/>
  /// </summary>
  IObservable<State> PlannerServiceStateObservable { get; }

  /// <summary>
  /// Current state (<see cref="State" />) of the planner service which essentially indicates
  /// whether or not this planner service is currently available for planning
  /// </summary>
  State PlannerServiceState { get; }

  /// <summary>
  /// If any reasoning needs to be provided for the current <see cref="State"/>
  /// </summary>
  string StateMessage { get; }

  /// <summary>
  /// Optional inputs that live on planners that can guide planning in certain directions.
  /// Unlike parameters which are generally supposed to be different per plan, the settings
  /// give the ability to have constants throughout the different plans.
  /// </summary>
  AresStruct Settings { get; }

  /// <summary>
  /// Updates the internal settings by overwriting the existing values with the ones provided by the
  /// passed in settings argument
  /// </summary>
  /// <param name="settings"></param>
  void UpdateSettings(AresStruct settings);

  /// <summary>
  /// This will return some custom settings that the planner supports.
  /// One of the build-in settings is the timeout that can tell ARES to wait a little longer in case planning takes awhile.
  /// Other settings are planner-specific and provided to ARES as descriptions. The user can then fill out the settings
  /// and send them back during planning.
  /// </summary>
  /// <param name="cancellationToken"></param>
  /// <returns></returns>
  Task<PlannerServiceCapabilities> GetCapabilities(CancellationToken cancellationToken  = default);

  /// <summary>
  /// Does the actual planning work.
  /// </summary>
  /// <param name="plannableParameters">A list of parameters that can be planned for.</param>
  /// <param name="previousExperiments">A list of past experiment history, designed to provide potential context to the planner.</param>
  /// <param name="analysisHistory">Additional analysis history generated by repeated experiments in ARES.</param>
  /// <param name="cancellationToken"></param>
  /// <returns></returns>
  Task<PlanResponse> Plan(IEnumerable<ParameterMetadata> plannableParameters,
    RequestMetadata metadata,
    IEnumerable<ExperimentOverview> previousExperiments,
    IEnumerable<Analysis> analysisHistory, 
    CancellationToken cancellationToken = default);

  /// <summary>
  /// Does the actual planning work.
  /// </summary>
  /// <param name="plannableParameters">A list of parameters that can be planned for.</param>
  /// <param name="previousExperiments">A list of past experiment history, designed to provide potential context to the planner service.</param>
  /// <param name="analysisHistory">Additional analysis history generated by repeated experiments in ARES</param>
  /// <param name="settings">Optional list of settings to influence the planner service.</param>
  /// <param name="cancellationToken"></param>
  /// <returns></returns>
  Task<PlanResponse> Plan(IEnumerable<ParameterMetadata> plannableParameters,
    RequestMetadata metadata,
    IEnumerable<ExperimentOverview> previousExperiments,
    IEnumerable<Analysis> analysisHistory,
    AresStruct settings,
    CancellationToken cancellationToken = default);

  /// <summary>
  /// How long do we expect the planner service to do its planning before ARES decided that planning has failed.
  /// This is here in case planning takes a few minutes.
  /// </summary>
  TimeSpan PlanningTimeout { get; }

  /// <summary>
  /// A list of planning methods reported to be available by the planner service
  /// </summary>
  IList<Planner> AvailablePlanners { get; }
}
