<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>DCS</Authors>
    <Company>DCS</Company>
    <Description>Library containing the command compilation and execution logic for campaigns.</Description>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(ProjectName).Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>


  <ItemGroup>
	  <PackageReference Include="ARES.Datamodel" Version="0.16.0" />
	  <PackageReference Include="CsvHelper" Version="33.1.0" />
	  <PackageReference Include="DynamicData" Version="9.4.1" />
	  <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
	  <PackageReference Include="Protobuf.System.Text.Json" Version="1.4.1" />
	  <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
	  <PackageReference Include="UnitsNet" Version="5.75.0" />
	</ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Ares.Device\AresDevicePluginBase\Ares.Device.csproj" />
  </ItemGroup>

</Project>
