<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Proto\Services.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AForge" Version="2.2.5" />
    <PackageReference Include="AForge.Imaging" Version="2.2.5" />
    <PackageReference Include="AForge.Video" Version="2.2.5" />
    <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />
    <PackageReference Include="Google.Protobuf" Version="3.33.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ares.Device.USB\Ares.Device.USB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\AresCameraConfig.proto" GrpcServices="None" />
    <Protobuf Include="Proto\Services.proto" ProtoRoot="Proto" />
  </ItemGroup>

</Project>
