syntax = "proto3";

package AresCamera.services;

import "google/protobuf/empty.proto";
import "AresCameraConfig.proto";

service AresCameraRpc {
	rpc CaptureImage(CameraRequest) returns (ImageResponse);
	rpc UpdateCameraSource(config.AresCameraConfig) returns (google.protobuf.Empty);
	rpc UpdateAvailableSources(CameraRequest) returns (AvailableSourcesResponse);

	rpc AddCamera(config.AresCameraConfig) returns (google.protobuf.Empty);
	rpc RemoveCamera(CameraRequest) returns (google.protobuf.Empty);
	rpc GetAllCameras(google.protobuf.Empty) returns (GetAllCamerasResponse);
	rpc UpdateCamera(config.AresCameraConfig) returns (google.protobuf.Empty);
}

message CameraRequest {
	string camera_id = 1;
}

message ImageResponse {
	bytes image_data = 1;
}

message UpdateSourceRequest {
	string camera_id = 1;
	string source_name = 2;
}

message AvailableSourcesResponse {
	repeated string available_sources = 1;
}

message CameraDescription {
	string id = 1;
	string name = 2;
}

message GetAllCamerasResponse {
	repeated CameraDescription cameras = 1;
}