<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<UserSecretsId>aspnet-UI-87962D8C-B573-4F3B-852F-E1DA10F52308</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ARES.Datamodel" Version="0.15.3-beta.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Grpc.AspNetCore.HealthChecks" Version="2.76.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Humanizer" Version="3.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Radzen.Blazor" Version="8.4.2" />
    <PackageReference Include="ReactiveUI.Blazor" Version="22.3.1" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="2.5.1" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Context" Version="4.6.5" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    <PackageReference Include="UnitsNet" Version="5.75.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Backend\Devices\Remote\" />
    <Folder Include="Pages\Settings\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AresMessaging\AresMessaging.csproj" />
    <ProjectReference Include="..\CrealityCamera\AresCamera.csproj" />
    <ProjectReference Include="..\PrusaMK4S\PrusaMK4S.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="FC2ClientCert.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
